// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sleuvhceuvkpaucnpail.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZXV2aGNldXZrcGF1Y25wYWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzM2NTYsImV4cCI6MjA3Mjg0OTY1Nn0.3R_uXaO-bQ_h9EFlKaG4l8Mil8a9J1odjH3OgQhMF3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});